### ISSUE TITLE
Can not import data into NebulaGraph

### ISSUE THREAD

**Issue by shaunT0ny** [nebula-contrib/NebulaGraph-Bench#85]
I'm stucking at **import data into NebulaGraph** with README guide

version
    nebula bench: 1.2.0
    nebula importer: 4.0
    nebula graph: 3.5

error info: `unsupported client version`
![image](https://github.com/nebula-contrib/NebulaGraph-Bench/assets/40254007/4e3c7cda-50a2-4630-a658-00bd669490f9)

generate `importer_config.yaml` snippets:
```yaml
version: v2
description: ldbc
removeTempFiles: false
clientSettings:
  retry: 3
  concurrency: 30 # number of graph clients
  channelBufferSize: 128
  space: mytest
  connection:
    user: ***********
    password: *************
    address: ***************
  postStart:
    commands: |
      CREATE SPACE IF NOT EXISTS mytest(PARTITION_NUM = 24, REPLICA_FACTOR = 3, vid_type = int64);
      USE mytest;
      CREATE TAG IF NOT EXISTS `Post`(`imageFile` string,`creationDate` datetime,`locationIP` string,`browserUsed` string,`language` string,`content` string,`length` int);
      CREATE TAG IF NOT EXISTS `Tagclass`(`name` string,`url` string);
      CREATE TAG IF NOT EXISTS `Tag`(`name` string,`url` string);
      CREATE TAG IF NOT EXISTS `Place`(`name` string,`url` string,`type` string);
      CREATE TAG IF NOT EXISTS `Person`(`firstName` string,`lastName` string,`gender` string,`birthday` string,`creationDate` datetime,`locationIP` string,`browserUsed` string);
      CREATE TAG IF NOT EXISTS `Organisation`(`type` string,`name` string,`url` string);
…………
```
**it looks likes NebulaGraph-Bench not update `nebula-import-vid-int.yaml.j2` in `template` folder to Nebula_Importer_V3's schema**
